name: Fetch Google Sheets Data

on:
  schedule:
    - cron: '0 6-23/3 * * *'  # Runs every 3 hours between 6 AM and 11 PM
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab.

permissions:
  contents: write  # Ensure the workflow has write access to contents

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure data directory exists
      run: mkdir -p data

    - name: Fetch Google Sheets Data
      run: |
          curl -L -s -o data/res.json "https://script.google.com/macros/s/AKfycbx9wzztut7gq4z2yBn1Fov7t-o2-RLu4QqLReCQfU7TnSopDBvrg_exud8RSIcKppOj/exec"
  
    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
        # Fetch latest changes and reset to origin
        git fetch origin
        git reset --hard origin/main
        
        git add data/res.json
        git commit -m "Update Google Sheets data" || echo "No changes to commit"
        git push origin HEAD:main || echo "Nothing to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
